#!/usr/bin/env python3
"""
generate.py — Arduino MIDI Controller Code Generator
Reads a layout JSON file and writes a ready-to-compile Arduino sketch.

Usage:
    python generate.py --config my_layout.json
    python generate.py --config my_layout.json --output firmware/firmware.ino

Requirements: Python 3.7+  (no extra packages needed)
"""

import json
import argparse
import os
import sys
import re
from pathlib import Path


# ── Helpers ──────────────────────────────────────────────────────────────────

def hex_to_rgb565(hex_color: str) -> str:
    """Convert #RRGGBB to RGB565 hex string for use in Arduino code."""
    hex_color = hex_color.lstrip("#")
    if len(hex_color) != 6:
        raise ValueError(f"Invalid color: #{hex_color}")
    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    rgb565 = (r5 << 11) | (g6 << 5) | b5
    return f"0x{rgb565:04X}"

def c(cfg: dict, key: str, fallback_hex: str = "#000000") -> str:
    """Look up a color in a control's colors block or return fallback."""
    colors = cfg.get("colors", {})
    return hex_to_rgb565(colors.get(key, fallback_hex))

def theme_color(theme: dict, key: str) -> str:
    return hex_to_rgb565(theme.get(key, "#000000"))

def safe_id(s: str) -> str:
    """Turn an id string into a valid C variable name fragment."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", s)

def midi_channel_0indexed(ch: int) -> int:
    return max(0, min(15, ch - 1))

def validate_config(cfg: dict):
    """Basic validation with clear error messages."""
    errors = []
    if "device" not in cfg:
        errors.append("Missing top-level 'device' block")
    if "theme" not in cfg:
        errors.append("Missing top-level 'theme' block")
    if "pages" not in cfg or not cfg["pages"]:
        errors.append("Missing or empty 'pages' array")

    seen_control_ids = set()
    for pi, page in enumerate(cfg.get("pages", [])):
        if "id" not in page:
            errors.append(f"Page {pi}: missing 'id'")
        if "label" not in page:
            errors.append(f"Page {pi}: missing 'label'")
        for ci, ctrl in enumerate(page.get("controls", [])):
            cid = ctrl.get("id", f"page{pi}_ctrl{ci}")
            if cid in seen_control_ids:
                errors.append(f"Duplicate control id: '{cid}'")
            seen_control_ids.add(cid)
            if "type" not in ctrl:
                errors.append(f"Control '{cid}': missing 'type'")
            elif ctrl["type"] not in ("button", "toggle", "slider"):
                errors.append(f"Control '{cid}': unknown type '{ctrl['type']}'")
            for field in ("x", "y", "w", "h"):
                if field not in ctrl:
                    errors.append(f"Control '{cid}': missing '{field}'")
            if "midi" not in ctrl:
                errors.append(f"Control '{cid}': missing 'midi' block")

    if errors:
        print("Config validation errors:")
        for e in errors:
            print(f"  ✗  {e}")
        sys.exit(1)


# ── Code generation sections ─────────────────────────────────────────────────

def gen_header(cfg: dict) -> str:
    device   = cfg["device"]
    name     = device.get("name", "MIDI Controller")
    rotation = device["screen"].get("rotation", 1)
    source   = cfg.get("_source_file", "unknown")
    return f"""// ================================================================
//  {name}
//  Generated by generate.py from: {source}
//  DO NOT EDIT THIS FILE DIRECTLY — edit the JSON config and regenerate.
//
//  LIBRARIES (Sketch → Manage Libraries):
//   - MCUFRIEND_kbv   by David Prentice
//   - Adafruit GFX    by Adafruit
//   - TouchScreen     by Adafruit
//
//  MIDI bridge: Hairless MIDI + loopMIDI (Win) / IAC Driver (Mac)
//  Hairless baud must be set to {device['midi']['baud']}
// ================================================================

#include <MCUFRIEND_kbv.h>
#include <Adafruit_GFX.h>
#include <TouchScreen.h>
"""

def gen_touch_defines(cfg: dict) -> str:
    t  = cfg["device"]["touch"]
    xp = t["pin_xp"]
    xm = t["pin_xm"]
    yp = t["pin_yp"]
    ym = t["pin_ym"]
    return f"""
// ── Touch pins ───────────────────────────────────────────────
#define XP   {xp}
#define XM   {xm}
#define YP   {yp}
#define YM   {ym}
TouchScreen ts(XP, YP, XM, YM, {t['resistance']});

#define TS_LEFT   {t['ts_left']}
#define TS_RT     {t['ts_right']}
#define TS_TOP    {t['ts_top']}
#define TS_BOT    {t['ts_bottom']}
#define MINPRESSURE  {t['min_pressure']}
#define MAXPRESSURE  {t['max_pressure']}
"""

def gen_display_defines(cfg: dict) -> str:
    s = cfg["device"]["screen"]
    return f"""
// ── Display ──────────────────────────────────────────────────
MCUFRIEND_kbv tft;
#define SCREEN_ROTATION {s['rotation']}
#define SCREEN_W        {s['width']}
#define SCREEN_H        {s['height']}
"""

def gen_midi_defines(cfg: dict) -> str:
    m  = cfg["device"]["midi"]
    ch = midi_channel_0indexed(m["channel"])
    return f"""
// ── MIDI ─────────────────────────────────────────────────────
#define MIDI_BAUD  {m['baud']}
#define MIDI_CH    {ch}
"""

def gen_color_defines(cfg: dict) -> str:
    theme = cfg["theme"]
    lines = ["\n// ── Theme colors (RGB565) ─────────────────────────────────"]
    for key, val in theme.items():
        try:
            rgb = hex_to_rgb565(val)
            cname = "T_" + key.upper()
            lines.append(f"#define {cname:<32} {rgb}")
        except ValueError:
            pass  # skip non-color values
    lines.append("")
    return "\n".join(lines)

def gen_page_and_control_enums(cfg: dict) -> str:
    pages = cfg["pages"]
    page_ids = [safe_id(p["id"]).upper() for p in pages]
    enum_vals = ", ".join(f"PAGE_{pid}" for pid in page_ids)

    # Count all controls for struct array size
    total = sum(len(p.get("controls", [])) for p in pages)

    return f"""
// ── Page enum ────────────────────────────────────────────────
enum PageID {{ {enum_vals} }};
#define NUM_PAGES {len(pages)}
int currentPage = 0;

// ── Control types ────────────────────────────────────────────
enum CtrlType {{ CTRL_BUTTON, CTRL_TOGGLE, CTRL_SLIDER }};

struct Control {{
  CtrlType type;
  int      page;
  int      x, y, w, h, radius;
  const char* label;
  uint8_t  label_size;
  // MIDI
  uint8_t  cc;
  uint8_t  value;        // button: send value; toggle/slider: unused here
  uint8_t  value_on;     // toggle on / slider max
  uint8_t  value_off;    // toggle off / slider min
  bool     send_release; // button only
  bool     is_slider_h;  // slider: true=horizontal false=vertical
  // Feedback
  bool     has_feedback;
  uint8_t  fb_cc;
  uint8_t  fb_value_on;
  uint8_t  fb_value_off;
  // Colors
  uint16_t col_bg,    col_border,    col_label;     // idle / off
  uint16_t col_bg2,   col_border2,   col_label2;    // active / on
  uint16_t col_track, col_fill,      col_val_text;  // slider extra
  // Runtime state
  bool     state;        // button: active; toggle: on; 
  int      slider_val;   // slider current value (0-127)
}};

#define NUM_CONTROLS {total}
Control controls[NUM_CONTROLS];
"""

def gen_control_init(cfg: dict) -> str:
    """Generate the populateControls() function that fills the controls array."""
    theme  = cfg["theme"]
    pages  = cfg["pages"]
    lines  = ["\nvoid populateControls() {", "  int i = 0;"]

    for pi, page in enumerate(pages):
        page_enum = f"PAGE_{safe_id(page['id']).upper()}"
        for ctrl in page.get("controls", []):
            ctype_map = {"button": "CTRL_BUTTON", "toggle": "CTRL_TOGGLE", "slider": "CTRL_SLIDER"}
            ctype = ctype_map[ctrl["type"]]
            cid   = safe_id(ctrl["id"])
            midi  = ctrl.get("midi", {})
            fb    = ctrl.get("feedback", {})
            colors = ctrl.get("colors", {})
            t     = ctrl["type"]

            def col(key, fallback_theme_key):
                return hex_to_rgb565(colors.get(key, theme.get(fallback_theme_key, "#000000")))

            if t == "button":
                bg     = col("idle_bg",      "button_bg")
                bd     = col("idle_border",  "button_border")
                lb     = col("idle_label",   "button_label")
                abg    = col("active_bg",    "button_active_bg")
                abd    = col("active_border","button_active_border")
                alb    = col("active_label", "button_active_label")
                trk    = "0x0000"; fil = "0x0000"; vt = "0x0000"
                v      = midi.get("value", 127)
                von    = midi.get("value", 127)
                voff   = 0
                sr     = "true" if midi.get("send_release", False) else "false"
                slider_h = "false"
                dv     = 0
            elif t == "toggle":
                bg     = col("off_bg",     "toggle_off_bg")
                bd     = col("off_border", "toggle_off_border")
                lb     = col("off_label",  "toggle_off_label")
                abg    = col("on_bg",      "toggle_on_bg")
                abd    = col("on_border",  "toggle_on_border")
                alb    = col("on_label",   "toggle_on_label")
                trk    = "0x0000"; fil = "0x0000"; vt = "0x0000"
                v      = midi.get("value_on", 127)
                von    = midi.get("value_on", 127)
                voff   = midi.get("value_off", 0)
                sr     = "false"
                slider_h = "false"
                dv     = 0
            else:  # slider
                bg     = col("track", "slider_track")
                bd     = col("track", "slider_track")
                lb     = col("label", "slider_label")
                abg    = col("fill",  "slider_fill")
                abd    = col("fill",  "slider_fill")
                alb    = col("label", "slider_label")
                trk    = col("track", "slider_track")
                fil    = col("fill",  "slider_fill")
                vt     = col("value_text", "slider_value")
                v      = 0
                von    = midi.get("value_max", 127)
                voff   = midi.get("value_min", 0)
                sr     = "false"
                slider_h = "true" if ctrl.get("orientation", "horizontal") == "horizontal" else "false"
                dv     = ctrl.get("default_value", 0)

            has_fb   = "true" if fb else "false"
            fb_cc    = fb.get("cc", 0)
            fb_von   = fb.get("value_on", 127)
            fb_voff  = fb.get("value_off", 0)

            label_escaped = ctrl["label"].replace('"', '\\"')

            lines.append(f"""
  // {ctrl['id']}  ({t}, page {pi})
  controls[i].type         = {ctype};
  controls[i].page         = {pi};
  controls[i].x            = {ctrl['x']};
  controls[i].y            = {ctrl['y']};
  controls[i].w            = {ctrl['w']};
  controls[i].h            = {ctrl['h']};
  controls[i].radius       = {ctrl.get('corner_radius', 8)};
  controls[i].label        = "{label_escaped}";
  controls[i].label_size   = {ctrl.get('label_size', 2)};
  controls[i].cc           = {midi.get('cc', 0)};
  controls[i].value        = {v};
  controls[i].value_on     = {von};
  controls[i].value_off    = {voff};
  controls[i].send_release = {sr};
  controls[i].is_slider_h  = {slider_h};
  controls[i].has_feedback = {has_fb};
  controls[i].fb_cc        = {fb_cc};
  controls[i].fb_value_on  = {fb_von};
  controls[i].fb_value_off = {fb_voff};
  controls[i].col_bg       = {bg};
  controls[i].col_border   = {bd};
  controls[i].col_label    = {lb};
  controls[i].col_bg2      = {abg};
  controls[i].col_border2  = {abd};
  controls[i].col_label2   = {alb};
  controls[i].col_track    = {trk};
  controls[i].col_fill     = {fil};
  controls[i].col_val_text = {vt};
  controls[i].state        = false;
  controls[i].slider_val   = {dv};
  i++;""")

    lines.append("}\n")
    return "\n".join(lines)

def gen_runtime(cfg: dict) -> str:
    """Generate the full runtime: setup, loop, draw, touch, MIDI functions."""
    theme  = cfg["theme"]
    pages  = cfg["pages"]
    device = cfg["device"]
    nav_h  = 20 if len(pages) > 1 else 0

    bg_color   = theme_color(theme, "background")
    nav_bg     = theme_color(theme, "nav_bg")
    nav_border = theme_color(theme, "nav_border")
    nav_act    = theme_color(theme, "nav_active")
    nav_inact  = theme_color(theme, "nav_inactive")
    st_bg      = theme_color(theme, "status_bg")
    st_txt     = theme_color(theme, "status_text")

    page_labels = [p["label"] for p in pages]
    pl_str = ", ".join(f'"{l}"' for l in page_labels)

    return f"""
// ── Nav bar height (0 if single page) ────────────────────────
#define NAV_H   {nav_h}

// Page labels for nav bar
const char* pageLabels[NUM_PAGES] = {{ {pl_str} }};

unsigned long lastTouchMs = 0;
#define DEBOUNCE_MS 180

// ── MIDI running-status byte for re-sync ─────────────────────
bool pressingControl = false;
int  pressingIndex   = -1;

// ================================================================
//  SETUP
// ================================================================
void setup() {{
  Serial.begin(MIDI_BAUD);

  uint16_t id = tft.readID();
  if (id == 0xD3D3 || id == 0x0000) id = 0x9486;
  tft.begin(id);
  tft.setRotation(SCREEN_ROTATION);

  populateControls();
  tft.fillScreen({bg_color});
  drawPage(currentPage);
}}

// ================================================================
//  LOOP
// ================================================================
void loop() {{
  handleTouch();
  readMIDI();
}}

// ================================================================
//  DRAW
// ================================================================
void drawPage(int page) {{
  tft.fillScreen({bg_color});
  for (int i = 0; i < NUM_CONTROLS; i++) {{
    if (controls[i].page == page) drawControl(i);
  }}
  if (NUM_PAGES > 1) drawNavBar();
}}

void drawControl(int i) {{
  Control& c = controls[i];
  switch (c.type) {{
    case CTRL_BUTTON: drawButton(i); break;
    case CTRL_TOGGLE: drawToggle(i); break;
    case CTRL_SLIDER: drawSlider(i); break;
  }}
}}

void drawButton(int i) {{
  Control& c = controls[i];
  uint16_t bg  = c.state ? c.col_bg2     : c.col_bg;
  uint16_t bd  = c.state ? c.col_border2 : c.col_border;
  uint16_t lbl = c.state ? c.col_label2  : c.col_label;

  tft.fillRoundRect(c.x, c.y, c.w, c.h, c.radius, bg);
  tft.drawRoundRect(c.x, c.y, c.w, c.h, c.radius, bd);
  if (c.state) tft.drawRoundRect(c.x+2, c.y+2, c.w-4, c.h-4, c.radius-2, bd);

  tft.setTextSize(c.label_size);
  tft.setTextColor(lbl);
  int tw = strlen(c.label) * 6 * c.label_size;
  int th = 8 * c.label_size;
  tft.setCursor(c.x + (c.w - tw)/2, c.y + (c.h - th)/2);
  tft.print(c.label);
}}

void drawToggle(int i) {{
  Control& c = controls[i];
  uint16_t bg  = c.state ? c.col_bg2     : c.col_bg;
  uint16_t bd  = c.state ? c.col_border2 : c.col_border;
  uint16_t lbl = c.state ? c.col_label2  : c.col_label;

  tft.fillRoundRect(c.x, c.y, c.w, c.h, c.radius, bg);
  tft.drawRoundRect(c.x, c.y, c.w, c.h, c.radius, bd);

  tft.setTextSize(c.label_size);
  tft.setTextColor(lbl);
  int tw = strlen(c.label) * 6 * c.label_size;
  int th = 8 * c.label_size;
  tft.setCursor(c.x + (c.w - tw)/2, c.y + (c.h - th)/2 - 4);
  tft.print(c.label);

  // ON/OFF indicator
  tft.setTextSize(1);
  tft.setTextColor(lbl);
  const char* stateStr = c.state ? "ON" : "OFF";
  int sw = strlen(stateStr) * 6;
  tft.setCursor(c.x + (c.w - sw)/2, c.y + c.h - 14);
  tft.print(stateStr);
}}

void drawSlider(int i) {{
  Control& c = controls[i];

  // Background track
  tft.fillRoundRect(c.x, c.y, c.w, c.h, c.radius, c.col_track);
  tft.drawRoundRect(c.x, c.y, c.w, c.h, c.radius, c.col_border);

  // Fill portion
  float frac = (float)(c.slider_val - c.value_off) / max(1, (int)(c.value_on - c.value_off));
  frac = constrain(frac, 0.0f, 1.0f);

  if (c.is_slider_h) {{
    int fillW = (int)(frac * (c.w - 4));
    if (fillW > 0)
      tft.fillRoundRect(c.x+2, c.y+2, fillW, c.h-4, max(0, c.radius-2), c.col_fill);
  }} else {{
    int fillH = (int)(frac * (c.h - 4));
    if (fillH > 0)
      tft.fillRoundRect(c.x+2, c.y + c.h - 2 - fillH, c.w-4, fillH, max(0, c.radius-2), c.col_fill);
  }}

  // Label
  tft.setTextSize(c.label_size);
  tft.setTextColor(c.col_label);
  int tw = strlen(c.label) * 6 * c.label_size;
  tft.setCursor(c.x + (c.w - tw)/2, c.y + 4);
  tft.print(c.label);

  // Value
  tft.setTextSize(1);
  tft.setTextColor(c.col_val_text);
  char vbuf[8];
  snprintf(vbuf, sizeof(vbuf), "%d", c.slider_val);
  int vw = strlen(vbuf) * 6;
  tft.setCursor(c.x + (c.w - vw)/2, c.y + c.h - 12);
  tft.print(vbuf);
}}

void drawNavBar() {{
  int y = SCREEN_H - NAV_H;
  tft.fillRect(0, y, SCREEN_W, NAV_H, {nav_bg});
  tft.drawFastHLine(0, y, SCREEN_W, {nav_border});

  // Dot indicators centered
  int dotSpacing = 16;
  int totalW = NUM_PAGES * dotSpacing;
  int startX = (SCREEN_W - totalW) / 2 + dotSpacing/2;

  for (int p = 0; p < NUM_PAGES; p++) {{
    int cx = startX + p * dotSpacing;
    int cy = y + NAV_H/2;
    if (p == currentPage) {{
      tft.fillCircle(cx, cy, 5, {nav_act});
    }} else {{
      tft.drawCircle(cx, cy, 4, {nav_inact});
    }}
  }}
}}

// ================================================================
//  TOUCH
// ================================================================
void handleTouch() {{
  TSPoint p = ts.getPoint();
  pinMode(XM, OUTPUT);
  pinMode(YP, OUTPUT);

  if (p.z < MINPRESSURE || p.z > MAXPRESSURE) {{
    // Finger lifted — handle button release
    if (pressingControl && pressingIndex >= 0) {{
      Control& c = controls[pressingIndex];
      if (c.type == CTRL_BUTTON && c.send_release) {{
        midiCC(c.cc, 0);
        c.state = false;
        drawControl(pressingIndex);
      }}
    }}
    pressingControl = false;
    pressingIndex   = -1;
    return;
  }}

  unsigned long now = millis();
  if (now - lastTouchMs < DEBOUNCE_MS) return;
  lastTouchMs = now;

  int tx = map(p.y, TS_LEFT, TS_RT,  0, SCREEN_W);
  int ty = map(p.x, TS_TOP,  TS_BOT, 0, SCREEN_H);
  tx = constrain(tx, 0, SCREEN_W - 1);
  ty = constrain(ty, 0, SCREEN_H - 1);

  // Nav bar tap
  if (NUM_PAGES > 1 && ty >= SCREEN_H - NAV_H) {{
    int dotSpacing = 16;
    int totalW = NUM_PAGES * dotSpacing;
    int startX = (SCREEN_W - totalW) / 2 + dotSpacing/2;
    for (int p2 = 0; p2 < NUM_PAGES; p2++) {{
      int cx = startX + p2 * dotSpacing;
      if (abs(tx - cx) < 12) {{
        if (p2 != currentPage) {{
          currentPage = p2;
          drawPage(currentPage);
        }}
        return;
      }}
    }}
    return;
  }}

  // Swipe detection — simple: check if tap is far left or right edge
  // (full swipe gesture would need tracking; this is a tap-zone approach)

  // Hit-test controls on current page
  for (int i = 0; i < NUM_CONTROLS; i++) {{
    Control& c = controls[i];
    if (c.page != currentPage) continue;
    if (tx >= c.x && tx <= c.x + c.w &&
        ty >= c.y && ty <= c.y + c.h) {{
      activateControl(i, tx, ty);
      return;
    }}
  }}
}}

void activateControl(int i, int tx, int ty) {{
  Control& c = controls[i];
  pressingControl = true;
  pressingIndex   = i;

  if (c.type == CTRL_BUTTON) {{
    c.state = true;
    drawControl(i);
    midiCC(c.cc, c.value);

  }} else if (c.type == CTRL_TOGGLE) {{
    c.state = !c.state;
    drawControl(i);
    midiCC(c.cc, c.state ? c.value_on : c.value_off);

  }} else if (c.type == CTRL_SLIDER) {{
    // Map touch position to 0-127
    int rawVal;
    if (c.is_slider_h) {{
      rawVal = map(tx, c.x, c.x + c.w, c.value_off, c.value_on);
    }} else {{
      rawVal = map(ty, c.y + c.h, c.y, c.value_off, c.value_on);
    }}
    rawVal = constrain(rawVal, min(c.value_off, c.value_on), max(c.value_off, c.value_on));
    if (rawVal != c.slider_val) {{
      c.slider_val = rawVal;
      drawControl(i);
      midiCC(c.cc, (uint8_t)rawVal);
    }}
  }}
}}

// ================================================================
//  MIDI OUT
// ================================================================
void midiCC(uint8_t cc, uint8_t value) {{
  Serial.write((byte)(0xB0 | MIDI_CH));
  Serial.write(cc);
  Serial.write(value);
}}

// ================================================================
//  MIDI IN
// ================================================================
void readMIDI() {{
  while (Serial.available() >= 3) {{
    byte s = Serial.read();
    if (!(s & 0x80)) continue;
    byte d1 = Serial.read();
    byte d2 = Serial.read();

    if ((s & 0xF0) == 0xB0 && (s & 0x0F) == MIDI_CH) {{
      // Find any control listening for this CC
      for (int i = 0; i < NUM_CONTROLS; i++) {{
        Control& c = controls[i];
        if (!c.has_feedback) continue;
        if (c.fb_cc != d1)   continue;

        if (c.type == CTRL_BUTTON) {{
          bool newState = (d2 == c.fb_value_on);
          if (newState != c.state) {{
            c.state = newState;
            if (c.page == currentPage) drawControl(i);
          }}
        }} else if (c.type == CTRL_TOGGLE) {{
          bool newState = (d2 >= 64);
          if (newState != c.state) {{
            c.state = newState;
            if (c.page == currentPage) drawControl(i);
          }}
        }} else if (c.type == CTRL_SLIDER) {{
          if (d2 != c.slider_val) {{
            c.slider_val = d2;
            if (c.page == currentPage) drawControl(i);
          }}
        }}
      }}
    }}
  }}
}}
"""

# ── Main ─────────────────────────────────────────────────────────────────────

def generate(config_path: str, output_path: str):
    with open(config_path, "r", encoding="utf-8") as f:
        # Strip JS-style // comments (JSON doesn't support them natively)
        raw = f.read()
        raw = re.sub(r"//[^\n]*", "", raw)
        cfg = json.loads(raw)

    cfg["_source_file"] = Path(config_path).name
    validate_config(cfg)

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    sketch = (
        gen_header(cfg)
        + gen_touch_defines(cfg)
        + gen_display_defines(cfg)
        + gen_midi_defines(cfg)
        + gen_color_defines(cfg)
        + gen_page_and_control_enums(cfg)
        + gen_control_init(cfg)
        + gen_runtime(cfg)
    )

    with open(out, "w", encoding="utf-8") as f:
        f.write(sketch)

    pages    = cfg["pages"]
    controls = sum(len(p.get("controls", [])) for p in pages)
    print(f"✓  Generated: {output_path}")
    print(f"   {len(pages)} page(s), {controls} control(s)")
    print(f"   Screen rotation: {cfg['device']['screen']['rotation']}")
    print(f"   MIDI channel: {cfg['device']['midi']['channel']}  baud: {cfg['device']['midi']['baud']}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate Arduino firmware from a MIDI controller layout JSON."
    )
    parser.add_argument(
        "--config", "-c",
        required=True,
        help="Path to layout JSON file (e.g. my_layout.json)"
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output .ino path. Default: firmware/<config_name>/firmware.ino"
    )
    args = parser.parse_args()

    if not os.path.exists(args.config):
        print(f"Error: config file not found: {args.config}")
        sys.exit(1)

    if args.output:
        output = args.output
    else:
        stem = Path(args.config).stem
        output = f"firmware/{stem}/{stem}.ino"

    generate(args.config, output)


if __name__ == "__main__":
    main()
